version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it-hub_api
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 80:8080
    env_file:
      - .production.env
  database:
    image: postgres
    container_name: project-db
    restart: unless-stopped
    env_file:
      - .production.env
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    name: project.db-volume